### ISSUE TITLE
Selecting Wavetables from SD card crashes the module

### ISSUE THREAD

**Issue by RyanPWM** [1V-Oct/3318_the_centre_releases#1]
1. Add WTO

2. Load

3. tables

4. select table

5. Crash (black screen)

The issue happens whenever I select a wavetable in all circumstances I have tried. The issue is independent of which wavetable I select.

**Comment by duddie** [comment]
This should be fixed by removing ability to load wavetables by Load button. Wavetables are supposed to be loaded from Patch menu.
