### ISSUE TITLE
[REQUEST] Allow users to select clockwise/anti-clockwise encoder operation

### ISSUE THREAD

**Issue by ExitChamber** [1V-Oct/3318_the_centre_releases#14]
I think it would be helpful to be able to select preferred orientation for the encoder scrolling through the menus.

**Comment by karnlund** [comment]
I find the encoder direction to be inconsistent.  In general I like clockwise to scroll down, counter clockwise to scroll up, clockwise to scroll right, and counter clockwise to scroll left.  Currently, left/right seems ok, but up/down is reversed.

**Comment by duddie** [comment]
That has been completed and is part of system settings for long time. :)
