### ISSUE TITLE
[REQUEST] Please add 'confirm' to Init

### ISSUE THREAD

**Issue by thegreenalien** [1V-Oct/3318_the_centre_releases#15]
On the main menu, please add a 'Confirm yes/no' 
or 'Save current patch yes/no'  popup to Init button. Without this, it's far too easy to accidentally press Init and erase your current patch.

**Comment by duddie** [comment]
It has been implemented. Any other locations need that?

**Comment by ExitChamber** [comment]
Might be worth adding to the delete command too
