### ISSUE TITLE
[REQUEST] Please add folder nesting to file tree

### ISSUE THREAD

**Issue by thegreenalien** [1V-Oct/3318_the_centre_releases#16]
At present, file system doesn't allow separate folders within categories, so all wavetables, for example, need to be stored together in the 'tables' category. This will make finding specific wavetables increasingly difficult as more are added.
Please add the option to group items within folders.

**Comment by ExitChamber** [comment]
Mine is working fine with wavetables in separate folders within the "tables" directory

![16334258918397554492227062574363](https://user-images.githubusercontent.com/87282758/135996951-1a9e1d3d-7631-493a-af8a-6e0c96ac7a8c.jpg)

**Comment by thegreenalien** [comment]
Very interesting. I tried several times, but the files were only visible in the base folders. I'll try again.

**Comment by ExitChamber** [comment]
How are you trying to load them? I was a bit confused at first until I realised that you need to select your wavetable by adding a WTO and then clicking the encoder at the wave display screen:

![16334336320495547405902793717529](https://user-images.githubusercontent.com/87282758/136015017-f3b8e90a-16df-4552-a80b-915a08a16318.jpg)

That should bring up the file structure as shown in that last pic.

**Comment by thegreenalien** [comment]
I got exactly to that stage, clicking the encoder just brought up a blank
screen. No problem loading wavetables when they are placed directly in the
'tables' directory.

**Comment by ExitChamber** [comment]
Oh, that's very odd. Sorry I'm out of suggestions.

**Comment by thegreenalien** [comment]
Funny, it's working fine now, no idea why ir wasn't working yesterday! Thanks for the feedback, issue closed.
