### ISSUE TITLE
[REQUEST] Add "Press Encoder to select wavetable" help text to the WTO

### ISSUE THREAD

**Issue by ExitChamber** [1V-Oct/3318_the_centre_releases#18]
Could this screen be changed to read the above instead of "* NO FILE LOADED *"?

![16334339317134243215922879561004](https://user-images.githubusercontent.com/87282758/136015707-d6032075-2f41-4d07-9de7-67965f7d6162.jpg)

I think it would help people starting to use it to get going a bit quicker.

**Comment by duddie** [comment]
Completed
