### ISSUE TITLE
Crash when browsing wavetable menu

### ISSUE THREAD

**Issue by RyanPWM** [1V-Oct/3318_the_centre_releases#2]
- WTO added in patching

- selected cjw wavetables

- went back into menu

- selected "user" folder

- press back button, to return to previous menu

- crash

**Comment by duddie** [comment]
This should be fixed with version 41.15

**Comment by duddie** [comment]
Another location for possible crash has been isolated. Fix deployed in 0.41.33

**Comment by Pipstapee** [comment]
This seems to be cause by WAV file size and or format. I've used several packs now with no issues with hanging, some just take longer to load.
