### ISSUE TITLE
[REQUEST] Assignment Pop-ups

### ISSUE THREAD

**Issue by ExitChamber** [1V-Oct/3318_the_centre_releases#24]
Would it be possible to display somewhere on the screen what each knob is assigned to when it is adjusted by hand?

Going back to a patch from a couple of days ago I'm finding myself having to go through all the modules to remind myself what is assigned to what.

**Comment by duddie** [comment]
Yep, I will do so

**Comment by ExitChamber** [comment]
I think the new patch screen covers this, going to close it.
