### ISSUE TITLE
Wavetable uploads aren't distributed evenly (different from how they appear in Serum)

### ISSUE THREAD

**Issue by RyanPWM** [1V-Oct/3318_the_centre_releases#3]
When uploading a wavetable 16 bit export from Serum, The Centre has many copies of the last table instead of the tables being distributed evenly, as they are in Serum.

**Comment by RyanPWM** [comment]
![File_000 (1)](https://user-images.githubusercontent.com/72544894/101739648-d4d1f600-3a95-11eb-9dbd-7106dbed9345.jpeg)

**Comment by RyanPWM** [comment]
![File_000 (2)](https://user-images.githubusercontent.com/72544894/101739661-d8fe1380-3a95-11eb-8793-828ccc3f79ee.jpeg)

**Comment by duddie** [comment]
This bug has been addresses in 0.41.33
