### ISSUE TITLE
[BUG] Adding waveform to second WTO crashes

### ISSUE THREAD

**Issue by thegreenalien** [1V-Oct/3318_the_centre_releases#31]
With one WTO up and running with waveform loaded, a second WTO is added. When the waveform for this WTO is selected, the unit crashes.
To test this I tried loading the same waveform (Producer hive SqFifth1) into both WTO, it crashed.
Tried with several waveforms, still crashes when second one is added.

**Comment by duddie** [comment]
Please see the private message on Discord. 
I have tried reproducing. I have 3 WTOs with different or same wavetables. Cannot reproduce.

**Comment by duddie** [comment]
I spent like 2 hours in different combinations tryin to reproduce this problem to not experiencing a single crash. If you can give me all details it will be much easier. Please mail me WAV files used (hopefuly you can recreate it with single wav). I assume you are using the latest firmware.

**Comment by thegreenalien** [comment]
I've tried it with a new system disc that just contains one set of tables,
it works fine. I'll now add more sets of tables, see what happens.

**Comment by thegreenalien** [comment]
I've found some wavetables that definitely cause problems, I've emailed you
a couple of zip files.

**Comment by duddie** [comment]
How is the problem now?

**Comment by duddie** [comment]
I hope all is good now?
