### ISSUE TITLE
[BUG] Selecting BRM creates VCA

### ISSUE THREAD

**Issue by thegreenalien** [1V-Oct/3318_the_centre_releases#33]
Can't create a new Ring Modulator, selecting BRM creates a new VCA

**Comment by duddie** [comment]
This has been solved. Now BRM (Balanced Ring Modulator) has two Audio inputs and the modulator input that allows to "pan" between two input sources when they modulate each other.

Please check and see if we can close this one or there is some more work that needs to be done.
