### ISSUE TITLE
[BUG] Loading a preset from SDcard causes a crash

### ISSUE THREAD

**Issue by markcrosbie** [1V-Oct/3318_the_centre_releases#44]
I created a preset yesterday that had 4 drum sample players in it. I powered down overnight (SDcard stayed in the module) and today when I power on and try to load the preset theCentre reboots and nothing loads.

I've attached the preset with a .txt extension (rename it to groove.vxp) and crash dump file with a .txt extension too.
[groove copy.txt](https://github.com/1V-Oct/3318_the_centre_releases/files/8325465/groove.copy.txt)
[crash_dump-0004.bin.txt](https://github.com/1V-Oct/3318_the_centre_releases/files/8325474/crash_dump-0004.bin.txt)

Pretty frustrating as I'd spent all last night getting the patch put together and was excited to finally have it working!

**Comment by markcrosbie** [comment]
Adding more; I was able to load this patch today (didn't do anything different so I don't know why it loaded ok) but then as I was playing it the Centre crashed and rebooted and the patch disappeared. Attaching the crash dump.

[crash_dump-0005.bin.zip](https://github.com/1V-Oct/3318_the_centre_releases/files/8328678/crash_dump-0005.bin.zip)

**Comment by duddie** [comment]
Hi Mark,

Can you mail me at lfo@1voct.com and I could send you test version to see if it solves your problem?

Thanks, kind regards, Duddie

**Comment by markcrosbie** [comment]
Sure thing - email sent.

**Comment by duddie** [comment]
Can you please confirm that the problem has been resolved?
