### ISSUE TITLE
Changing wave polyphony.

### ISSUE THREAD

**Issue by Pipstapee** [1V-Oct/3318_the_centre_releases#8]
Changing wave polyphony causes crash. Latest firmware.

**Comment by ExitChamber** [comment]
Just had this one, going beyond 4 in the polyphony menu brings up a couple of weird results then a reset.

**Comment by duddie** [comment]
Resolved in 0.71 but might have other issues

**Comment by ExitChamber** [comment]
Yep, working fine now
