### ISSUE TITLE
ENV options and default trigger sources?

### ISSUE THREAD

**Issue by Pipstapee** [1V-Oct/3318_the_centre_releases#9]
My module has something modulating it without an cv or gate source patched.
If I add an ENV it cycles as if it were being triggered. Is there an internal source that is default to the ENV?
You also have audio in and out options for the ENV when it's a modulation source.

**Comment by duddie** [comment]
The trigger was always ON for ENV. Already patched in new version.

**Comment by Pipstapee** [comment]
We couldn't use the update on the module you sent me and had to flash the firmware with the new version, Drop me a DM in Discord with the new version to test.
